# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTjuzdOBCcvLnMkHXLnGVSHtkyLELofM
"""

import pandas as pd
import numpy as np
import seaborn as sns
df=sns.load_dataset('iris')
print("SHAPE:",df.shape)
print("COLS:", df.columns)
print(df.head)

#statistical summary
print(df.describe)

#missing values
print(df.isna().sum())
#no missing values found

import matplotlib.pyplot as plt

df = sns.load_dataset('iris')
plt.figure(figsize=(8, 6))
sns.scatterplot(data=df, x='sepal_length', y='sepal_width', hue='species')
plt.title('Sepal Length vs Sepal Width by Species')
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10,8))
sns.boxplot(data=df[['sepal_length','sepal_width' , 'petal_length' ,'petal_width','species']] )
plt.title("boxplot of dataset iris")
plt.ylabel('Centimeters')
plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('iris')

plt.figure(figsize=(10, 4))

# Left histogram - Sepal Length
plt.subplot(1, 2, 1)
plt.hist(df['sepal_length'], bins=15, color='skyblue', edgecolor='black', alpha=0.7)
plt.xlabel('Centimeters')
plt.ylabel('Frequency')
plt.title('Distribution of Sepal Length')

# Right histogram - Petal Length
plt.subplot(1, 2, 2)
plt.hist(df['petal_length'], bins=15, color='salmon', edgecolor='black', alpha=0.7)
plt.xlabel('Centimeters')
plt.ylabel('Frequency')
plt.title('Distribution of Petal Length')

plt.tight_layout()
plt.show()